### ISSUE TITLE
ImportError with tensorflow settings

### ISSUE THREAD

**Issue by smcveigh-phunware** [GPflow/GPflowOpt#95]
Branch:

- master: ae76144

Platform:

- macOS 10.13.2 (17C88)

Install method:

- install TensorFlow RC 1.4 from source (defaults, i.e. CPU optimization only)
- create py venv w/ 3.6.3
- install tensorflow build package to venv
- install gpflow from master clone to venv  via `pip install .`
- install gpflowopt from master clone to venv  via `pip install .`

In ipython kernel:

```python
[1] import gpflow as gp
Backend MacOSX is interactive backend. Turning interactive mode on.
[2] import gpflowopt as gpo
```
```Python traceback
Traceback (most recent call last):
  File "[...]/venv/default/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-bfed0eb53e8c>", line 1, in <module>
    import gpflowopt as gpo
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "[...]/venv/default/lib/python3.6/site-packages/gpflowopt/__init__.py", line 15, in <module>
    from . import acquisition
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "[...]/venv/default/lib/python3.6/site-packages/gpflowopt/acquisition/__init__.py", line 16, in <module>
    from .acquisition import Acquisition, AcquisitionAggregation, AcquisitionProduct, AcquisitionSum, MCMCAcquistion
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "[...]/venv/default/lib/python3.6/site-packages/gpflowopt/acquisition/acquisition.py", line 15, in <module>
    from ..scaling import DataScaler
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "[...]/venv/default/lib/python3.6/site-packages/gpflowopt/scaling.py", line 15, in <module>
    from gpflow.param import DataHolder, AutoFlow
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "[...]/venv/default/lib/python3.6/site-packages/gpflow/param.py", line 22, in <module>
    from . import session as session_mngr
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "[...]/venv/default/lib/python3.6/site-packages/gpflow/session.py", line 6, in <module>
    from ._settings import settings
ImportError: cannot import name 'settings'
```

**Comment by javdrher** [comment]
Hi @smcveigh-phunware , and thank you for your interest in GPflowOpt!

The GPflow master is the latest version (1.0), which is quite recent and introduced some changes in the API's. I believe this causes your problem. We are working on a new version of GPflowOpt which is compatible ( #91 for work in progress ). For now, the latest GPflow we support is 0.4.0, if you follow the installation instructions from the docs, it should be automatically installed.
